BATCH_SIZE = 32 # Batch sized used for traing.
EPOCHS = 100
LEARNING_RATE = 1e-4
PATH2SAVE_MODELS = "models"
DATA_SET_DIR = "/home/mtk/iCog/projects/emopy/dataset/all"
LOG_DIR = "logs"
STEPS_PER_EPOCH = 1000
NETWORK_TYPE = "mi" # mi for multi input or si for single input
AUGMENTATION = True